volumes:
  db_data:

services:
  cli:
    image: local/dtrack-cli:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./.volumes/db:/data:rw

  db:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dtrack
      - POSTGRES_PASSWORD=dtrack
      - POSTGRES_DB=dtrack
    volumes:
      - db_data:/var/lib/postgresql/18/docker
      - ./scripts/init/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
