version: "3"

silent: true

vars:
  PYTHON_VERSION: "3.14"

tasks:
  default:
    desc: Run the default task
    cmd: task init

  init:
    desc: Initialize the project
    cmds:
      - uv python install {{.PYTHON_VERSION}} --compile-bytecode
      - uv venv --python {{.PYTHON_VERSION}} --clear
      - uv sync --compile-bytecode

  lint:
    desc: "Run linters to check code quality."
    cmds:
      - uv run ruff check {{.CLI_ARGS}}

  fmt:
    desc: "Format code using uv."
    cmds:
      - uv run ruff format {{.CLI_ARGS}}

  type:
    desc: "Run type checking using mypy."
    cmds:
      - uv run ty check {{.CLI_ARGS}}

  run:
    desc: "Run the CLI entrypoint"
    cmds:
      - uv run python -m dtrack {{.CLI_ARGS}}

  test:
    desc: "Run tests."
    cmds:
      - uv run pytest --cov=src {{.CLI_ARGS}}

  db:migrate:
    desc: "Run the migration CLI"
    cmds:
      - uv run dtrack migrate {{.CLI_ARGS}}
